export const API_ENDPOINT = 'http://5b2c1f9147a7720014ca862a.mockapi.io/percentages'
export const FETCH_PERCENTAGES_REQUEST = 'FETCH_PERCENTAGES_REQUEST'
export const FETCH_PERCENTAGES_SUCCESS = 'FETCH_PERCENTAGES_SUCCESS'
export const FETCH_PERCENTAGES_FAILED = 'FETCH_PERCENTAGES_FAILED'
